### ISSUE TITLE
No marker

### ISSUE THREAD

**Issue by nhokhuy197** [HumanTree92/esx_advancedhospital#1]
Script work fine but there is no marker to use, like a circle i believe? i tried to disable npc ped but didnt work as well

**Comment by balancedliferp** [comment]
I am having the same issue. I get this error. It did not work when I first installed it. I tried changing some locations and that is when I noticed it but even in the beginning, I was not getting the marker. If there is anything you would like me to try please let me know. If you want to hop on and look at stuff for yourself I can arrange that too.
![hospitalerror](https://user-images.githubusercontent.com/56375000/76590432-6d195b00-64c3-11ea-9f93-b94449b60711.jpg)
I have since done a full reinstall and checked that I had all needed resources (I did have them). Still not working and have changed nothing this time.

**Comment by HumanTree92** [comment]
This should be fixed now.
